### ISSUE TITLE
Manage models through code

### ISSUE THREAD

**Issue by joshpalmeroc** [kontent-ai/data-ops#109]
### Motivation

Why is this feature required? What problems does it solve?

Managing the same models across multiple projects can become cumbersome utilizing the Kontent UI Dashboard. For example if I wanted to have a "Image" model that I will use for 3 projects I need to go into those 3 projects individually and add all the same fields 3 times. The data-ops tool somewhat solves this issue by having a JSON representation of models in code you can use. The problem I have is that using JSON to construct models is error prone to typos or missing required fields.

### Proposed solution

An ideal solution for the above problems.

I would love to see some sort of typescript library that can be used to manage your content model through code. This way i could easily just copy the code snippets for the models between different codebases and bootstrap kontent projects very quickly. My models would also be tracked through source control and i would get autocompletion when creating fields.

```ts
export const ImageModel = Kontent.model({
    image: Kontent.media().allowedTypes(['jpg', 'png']).required(),
    caption: Kontent.richText(),
    alt: Kontent.text().required(),
    width: Kontent.number().required(),
    height: Kontent.number().required(),
})

export const PostModel = Kontent.model({
    title: Kontent.text().default('This is a Post title').required(),
    description: Kontent.richText(),
    completed: Kontent.multipleChoice(['true','false']).default('true').required()
})
```

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

Some inspiration came from using popular ORM libraries like Prisma, Drizzle.

Also some inspiration from AWS Amplify https://docs.amplify.aws/react/build-a-backend/data/set-up-data/

**Comment by IvanKiral** [comment]
Hey @joshpalmeroc, thank you for your issue.

We were also exploring the idea of a "Model as Code" approach and may incorporate it in the future. However, we chose the JSON structure for now, as it is better documented and thoroughly explained in our [Learn Portal](https://kontent.ai/learn/docs/apis/openapi/management-api-v2/). 

On the other side, we have exposed the [types that are used by sync functionality](https://github.com/kontent-ai/data-ops/blob/main/src/public.ts) (on lines `14-24`). You can use those types to create a transformer that converts code into the folder structure with JSON files required by the sync function. For instance, you could define objects for the model using those types and then implement a function that serializes these objects into JSON and generates the corresponding files. While this approach might not directly resolve the issue between the codebases, it could be a workable solution with some creative adjustments.

Regarding the library request, I might propose it for prioritization in the new year. However, I can't guarantee that it will be a priority at this time. :/

**Comment by joshpalmeroc** [comment]
Thanks for the reply back! Ill take a look at using this transformer approach you mentioned. I look forward to future improvements.
