### ISSUE TITLE
Clean is an unknown argument

### ISSUE THREAD

**Issue by laststandjam** [kontent-ai/data-ops#36]
### Brief bug description

Trying to run clean command. Returns with error "Unknown arguments: environmentId, apiKey, clean" 

### Repro steps

Run command as according to read me
`npx @kontent-ai/data-ops clean --environmentId <target-environment-id> --apiKey <Management-API-key>`

### Test environment
data-ops@1.0.1

**Comment by pokornyd** [comment]
hello and thanks for your submission. minor version was not released following the merge to main. [v1.1.0](https://github.com/kontent-ai/data-ops/releases/tag/1.1.0) is now released and includes the `clean` operation.
