### ISSUE TITLE
"sync-model run" fails when an image is used within the content type guidelines.

### ISSUE THREAD

**Issue by jf22873** [kontent-ai/data-ops#58]
### Brief bug description

When I use the "sync model run" command to sync 2 models, it fails to sync the target environment in scenarios where an image is used inside "guidelines"

### Repro steps

1. Create a content type that contains an image in the guidelines.
2. Run "sync-model run"
Command runs successfully although running "sync model diff" after completion of previous command shows the environments have not been synced.

### Expected behaviour
The environments are synced

### Test environment

 - Windows 10 Enterprise
 - Powershell

### Additional context
The diff tool shows the figure as follows: `<figure  data-asset-id=\"6c321afe-390d-4836-a3cd-5de721f00204\"><img src=\"#\"  data-asset-id=\"6c321afe-390d-4836-a3cd-5de721f00204\"></figure>`

If the figure is not present the tool works fine.

**Comment by IvanKiral** [comment]
As this issue has been inactive for a while and we haven't received any recent updates, I'm going to close it for now. If you're still experiencing the problem or have more information to provide, feel free to reopen the issue or create a new one.

Thank you for your contribution!
