### ISSUE TITLE
Exports defined in public.js are not able to be imported

### ISSUE THREAD

**Issue by nkooman-bzs** [kontent-ai/data-ops#76]
### Brief bug description

Functions and types exported via the `public.js` file do not appear in package exports. When looking at the definition I am brought to an empty `index.d.ts` instead of `public.d.ts` described in the `package.json` under `exports`.

### Repro steps

1. Install Data Ops via npm
2. Attempt to import functions or types described in the documentation
3. See that you are unable to import anything.

### Expected behavior

I should be able to import various functions and types to programmatically run Data Ops commands.

### Test environment

 - Data Ops 1.6.1
 - Windows 11
 - Node.js 20.17.0
 - TypeScript 5.4.5

### Screenshots

![image](https://github.com/user-attachments/assets/cb9c22bc-6d68-4369-80c2-b3067dcd29b4)

![image](https://github.com/user-attachments/assets/02df5a7f-73f1-4736-9ec0-4492cdfb70db)

**Comment by IvanKiral** [comment]
Hey @nkooman-bzs,

I tried reproducing the steps you mentioned, and it works fine for me. 
<img width="1675" alt="image" src="https://github.com/user-attachments/assets/97b7e176-882c-4822-b359-717a42cfa8b4">

I tried to run it with tsx.

Are you sure, you have the right version of data-ops installed? Can you check the `package.json` of data-ops inside  your `node_modules` folder? :)

**Comment by IvanKiral** [comment]
I was able to get to the error. It worked for me because I had `"resolvePackageJsonImports": true` in `package.json`.  We will try to update some properties in `package.json` and see whether it would fix it.

**Comment by nkooman-bzs** [comment]
@IvanKiral Adding that property and updating my module resolution fixed the issue. Thanks for the assistance.
