### ISSUE TITLE
Expose more internal methods for individual use

### ISSUE THREAD

**Issue by nkooman-bzs** [kontent-ai/data-ops#77]
### Motivation

I'd like to be able to leverage diffing logic defined in this library for individual use cases rather than all in one go.
For example, when writing a script to handle migrating assets between Kontent.ai environments, I'd like to be able to also compare and sync asset folders to ensure that all folders exist before attempting to move assets.

### Proposed solution

Export more functions via `public.js`. 

### Additional context

#76 needs to be resolved before this is possible.

**Comment by IvanKiral** [comment]
Hey @nkooman-bzs 

Thanks for the issue.
What functions would you like to see exported?

**Comment by IvanKiral** [comment]
I see your use case.  
I will think about the solution - we will probably expose the functions you want or update the existing diffEnvironment function and add some supporting to it.

**Comment by IvanKiral** [comment]
Hey @nkooman-bzs.

I am thinking about exposing the `diff` functionality through `diffEnvrironments` function - that one would load source and target model and return `DiffModel` object. However, DiffModel uses the data-ops internal patch operations to update the entity. Those operations needs to be additionally processed before syncing. That would need to be documented, and also some other functions would need to be exposed like `printDiff` or `createAdvancedDiff`. That led me to question whether it is worth exposing that function or creating some new for comparing the environments. What exactly would you like to do with the `DiffModel` object? Do you only want to see whether there are empty properties or even something else?

**Comment by IvanKiral** [comment]
We are working on partial sync, where you would be able to define which entities you want to sync. Like there would be a parameter `--entities` in which you would define assetFolders and then only assetFolders would sync. Would that help you?

**Comment by nkooman-bzs** [comment]
If I'm able to do so programmatically, I think that would work.

**Comment by IvanKiral** [comment]
Hey @nkooman-bzs,

partial sync is now available in data-ops 2.0 :) Let me know if it fixes your use case. 

Thanks

**Comment by nkooman-bzs** [comment]
@IvanKiral unfortunately my current project has a dependency on migration-toolkit@1.x. I will not be able to verify directly whether or not this works. However, I have reviewed the new changes and from what I can tell this will absolutely resolve my issue. These changes are great, thanks!
