### ISSUE TITLE
Adding migration to migrationsFolder ./src broken

### ISSUE THREAD

**Issue by Freekbron** [kontent-ai/data-ops#79]
### Brief bug description

When running the add script eg:
`data-ops migrations add --name 02_test2 --migrationsFolder ./src`

The migrationsFolder isn't picked up, all migrations added go to the root folder.

### Expected behavior

`--migrationsFolder ./src` should place my file here:
`src/02_test2ts`
not in the root.

### Test environment

Node v20.17.0
MacOS

### Additional context

There seems to be a difference in the src an the build:

https://github.com/kontent-ai/data-ops/blob/main/src/modules/migrations/add.ts

```
const folderPath = params.migrationsFolder ?? process.cwd();
```

@kontent-ai/data-ops/build/src/commands/migrations/add/add.js:48

```
const folderPath = params.folder ?? process.cwd();

# this should be 
const folderPath = params.migrationsFolder ?? process.cwd();
```

**Comment by IvanKiral** [comment]
Hey @Freekbron,

what version of data-ops are you using?

**Comment by Freekbron** [comment]
I was using `"@kontent-ai/data-ops": "^1.5.0"` like in the [migrations-boilerplate](https://github.com/kontent-ai/migrations-boilerplate). With upgrading to `^1.6.1`, adding a migration works like expected!
