### ISSUE TITLE
Configuration for migrations with environment variables

### ISSUE THREAD

**Issue by Freekbron** [kontent-ai/data-ops#90]
### Question

My migrations work with `--configFile`. But environment variables like `DATA_OPS_ENVIRONMENT_ID=xxx` and `DATA_OPS_API_KEY=xxx` don't seem to work. I prefer environment variables because it makes switching environments easier.

[The documentation in the READ.ME](https://github.com/kontent-ai/data-ops/blob/main/README.md#configuration) about this seems to be cut off. 

I can't find anything with `DATA_OPS` [in the source of this repository](https://github.com/search?q=repo%3Akontent-ai%2Fdata-ops%20DATA_OPS&type=code)

Is this already implemented?

**Comment by JiriLojda** [comment]
Hi @Freekbron,

Thank you for submitting the issue. Unfortunately, I am not able to reproduce the issue with the latest version of `data-ops`. (I used a call like this `DATA_OPS_API_KEY=*** DATA_OPS_ENVIRONMENT_ID=*** npx @kontent-ai/data-ops@latest export`) What shell are you using to call `data-ops`? The example we have in the `README.md` file works in `bash` but does not have to work in other shells. Please, make sure that the environment variables you define are accessible to the `data-ops` process.

Regarding our code, the functionality is provided by the [`yargs`](https://yargs.js.org/docs/#api-reference-envprefix) library. You can find it used [here](https://github.com/kontent-ai/data-ops/blob/12d78fcbe3fd6786e84a7bbd2ad1bf2a360a2c21/src/index.ts#L23).

Another thing to mention is that environment variables are only accepted when you run `data-ops` using the CLI. If you are using the [TS/JS API](https://github.com/kontent-ai/data-ops/blob/main/src/commands/importExport/README.md#import-programmatically), environment variables are not accepted.

**Comment by JiriLojda** [comment]
@Freekbron the `migrations-boilarplate` is using the CLI. It definitely should work with environment variables. Just make sure that the variables are reaching the `data-ops` process. (e.g. if you set them like this `'runMigrations': 'DATA_OPS_API_KEY=*** tsc && data-ops ...'`, they will not be accessible to `data-ops`) The shell environment can also influence this. You can use a package like [`cross-env`](https://www.npmjs.com/package/cross-env) to make sure the variables are properly defined on whatever operating system you use.
Can you share the command you use to call `data-ops`?

**Comment by Freekbron** [comment]
@JiriLojda currently I'm using this:

```
"migrate:all": "tsc && data-ops migrations run --configFile ./migrationsParams.json --all",
```

So I need to make my own script where I pass my `.env` variables right?

**Comment by JiriLojda** [comment]
@Freekbron If you want to pass environment variables from a `.env` file to a CLI command you'll need to use a tool to do that. For example with [dotenv-cli](https://www.npmjs.com/package/dotenv-cli) you can call data ops like this `tsc && dotenv -- data-ops migrations run --all`.

**Comment by Freekbron** [comment]
That works, thanks for helping out!
